---
version: 0.2
phases:
  install:
    commands:
      # - echo Logging in to Amazon ECR...
      - aws --version
      - sudo rm -fr $(which aws)
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -qq awscliv2.zip
      - sudo ./aws/install
      - aws --version
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/darwin/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
  pre_build:
    commands:
      - sed -i 's@CONTAINER_IMAGE@'"$DOCKER_USER/$IMAGE_REPO_NAME:latest"'@' k8s/deployment.yaml
      - sed -i 's@APPNAME@'"$APPNAME"'@' k8s/deployment.yaml
      - sed -i 's@ENV@'"$ENVIRONMENT"'@' k8s/deployment.yaml
      - sed -i 's@APPNAME@'"$APPNAME"'@' k8s/service.yaml
      - sed -i 's@ENV@'"$ENVIRONMENT"'@' k8s/service.yaml
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      ## Enable the below line if you want to create your DB and other secure parameters to the .env/config files. make sure to grant access to the SSM parameter store.
      ## - aws ssm get-parameter --with-decryption --name $WHATEVERTHEPARAMETERNAMR --region $REGION | jq '.Parameter.Value' > .env
      - echo  "Building...".

  post_build:
    commands:
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - printf '[{"name":"k8s-deployment","imageUri":"%s"}]' $DOCKER_USER/$IMAGE_REPO_NAME:latest > build.json
artifacts:
  files: build.json
