apiVersion: v1
kind: Namespace
metadata:
  name: APPNAME
---
apiVersion: apps/v1
kind: Deployment
namespace: 
metadata:
  name: APPNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
        - name: APPNAME
          image: CONTAINER_IMAGE
        securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: http
          env:
            - name: NUXT_HOST
              value: '0.0.0.0'
            - name: NUXT_PORT
              value: '80'
            - name: PORT
              value: '80'
            - name: NODE_ENV
              value: production
            - name: ACCOUNT_HOST_URL
              value: https://api.getwelp.co.uk/accounts/v0
            - name: BASEURL_HOST
              value: https://api.getwelp.co.uk/core/v0
            - name: RETURN_URL
              value: https://app.getwelp.co.uk/Dashboard
