apiVersion: v1
kind: Namespace
metadata:
  name: APPNAME
---
apiVersion: apps/v1
kind: Deployment
namespace: 
metadata:
  name: APPNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
        - name: APPNAME
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
              name: http
          env:
            - name: NUXT_HOST
              value: '0.0.0.0'
            - name: NUXT_PORT
              value: '80'
            - name: PORT
              value: '80'
            - name: NODE_ENV
              value: production
            - name: ACCOUNT_HOST_URL
              value: https://api.getwelp.com/accounts/v0
            - name: SCHEDULER_HOST
              value: https://api.getwelp.com/scheduler/v0
            - name: BASEURL_HOST
              value: https://api.getwelp.com/core/v0
            - name: STRIPE_RETURN
              value: https://app.getwelp.com/Dashboard
            - name: QUICKBLOX_AUTH_KEY
              value: E7jN9O53RLe67qx
            - name: QUICKBLOX_AUTH_SECRET
              value: BesJU5mLLs2vkHX
            - name: QUICKBLOX_APPLICATION_ID
              value: '91841'
            - name: QUICKBLOX_ACCOUNT_KEY
              value: X-zxyGoLuAxMAHEJ7vog
            - name: QUICKBLOX_BASE_URL
              value: https://api.quickblox.com
            - name: PAYMENT_HOST_URL
              value: https://api.getwelp.com/payments/v0
            - name: SENDBIRD_APP_ID
              value: F8F1D048-D132-4645-95FC-6B561F449FB4

