---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: APPNAME
  name: APPNAME
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    app: APPNAME
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: APPNAME
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - staging.getwelp.co.uk
      - app.getwelp.com
      secretName: staging-getwelp-co-uk-tls-2
  rules:
  - host: staging.getwelp.co.uk
    http:
      paths:
      - backend:
          serviceName: APPNAME
          servicePort: 80
        path: /
  - host: app.getwelp.com
    http:
      paths:
      - backend:
          serviceName: APPNAME
          servicePort: 80
        path: /
