export const TourOption = {
  nextLabel: "Next",
  prevLabel: "Back",
  skipLabel: "",
  doneLabel: "Got it!",
  hidePrev: true,
  hideNext: false,
  nextToDone: true,
  tooltipPosition: "bottom",
  tooltipClass: "",
  highlightClass: "",
  exitOnEsc: true,
  exitOnOverlayClick: true,
  showStepNumbers: false,
  keyboardNavigation: true,
  showButtons: true,
  showBullets: true,
  showProgress: false,
  scrollToElement: true,
  scrollTo: "element",
  scrollPadding: 30,
  overlayOpacity: 0.5,
  autoPosition: true,
  positionPrecedence: ["bottom", "top", "right", "left"],
  disableInteraction: false,
  helperElementPadding: 5,
  hintPosition: "top-middle",
  hintAnimation: true,
  buttonClass: "bg-white rounded px-6 py-1 text-blue-500",
  progressBarAdditionalClass: false,
};
